version: '3'

services: 
  database: 
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: "sbo"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - "./sql/:/docker-entrypoint-initdb.d/"
  api:
    build: .
    container_name: api
    depends_on:
      - "database"
    ports:
      - "5000:5000"
    environment:
      APP_PORT: 5000
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_DBNAME: sbo
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 123
