version: '3'

services: 
  database: 
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: "sbo"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - "./sql/:/docker-entrypoint-initdb.d/"
  api:
    build: .
    container_name: api
    depends_on:
      - "database"
    ports:
      - "5000:5000"
