apiVersion: v1
kind: Service
metadata:
  name: api-service

spec:
  selector:
    app: api-sob
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
